line-length = 120

[lint]
ignore = [
    "F403", # *-imports
    "ANN002", # annotation for *args,
    "ANN003", # annotation for **kwargs
    "ANN101", # annotate "self",
    "ANN102", # annotate "cls",
    "ANN204",  # return type for special functions (__init__),
    "ANN401"  # allow 'Any'
]

select = [
    "F",   # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "W",   # https://docs.astral.sh/ruff/rules/#warning-w
    "E",   # https://docs.astral.sh/ruff/rules/#error-e
    "ANN", # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    "B",   # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
]

exclude = [
]
